version: '3.8'

volumes:
#  grafana_storage: {}
  postgres_storage: {}

services:
  postgres:
    image: postgres:15.3
    env_file: '.env'
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - 'postgres_storage:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

  web-service:
    build: .
    env_file: '.env'
    volumes:
      - '../src:/var/web'
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8003:8000'
    depends_on:
      - postgres

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus.yml:/prometheus/prometheus.yml
#    command:
#      - '--config.file=/prometheus/prometheus.yml'
#      - '--web.enable-lifecycle'
#    ports:
#      - '9090:9090'
#
#  grafana:
#    image: grafana/grafana-enterprise
#    container_name: grafana
#    restart: unless-stopped
#    ports:
#     - '3000:3000'
#    volumes:
#     - 'grafana_storage:/var/lib/grafana'
