global:
  scrape_interval: 10s 

scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'test'
    scrape_interval: 5s
    metrics_path: /metrics

    static_configs:
      - targets: ['host.docker.internal:8000']
